version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
      - "3001:3001"
    volumes:
      - ./app:/usr/server/app
      - ./public:/usr/server/public
volumes:
  mysql_volume:
